# Generated by Django 3.2.6 on 2021-08-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='serialnum',
            field=models.CharField(default='1', max_length=15),
        ),
    ]
