# Generated by Django 3.2.6 on 2021-08-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_member_serialnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='serialnum',
            field=models.IntegerField(default='1', max_length=15),
        ),
    ]
