# Generated by Django 3.2.6 on 2021-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20211024_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Category_name',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='KAWAII', max_length=255),
        ),
    ]
