# Generated by Django 3.2.6 on 2021-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_member_serialnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='serialnum',
            field=models.IntegerField(default='1'),
        ),
    ]
